[project]
name = "invoices"
version = "0.1.0"
description = "Basic TOML to PDF invoice generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "reportlab>=4.4.2",
    "toml>=0.10.2",
]
